
name: Elliott's Engineering Extravaganza
highlighter: rouge
markdown: kramdown
disqus: # disqus-username
google_analytics_id: '' # XY-99999999-9

description: Elliott's Engineering Extravaganza

author: Elliott Birch
  name: 'Elliott Birch'
  email: 'elliottabirch@gmail.com'
  github: elliottabirch
  linkedin: elliottabirch
  email_md5: 'elliottabirch@gmail.com' # used for gravatar sidebar user image

BASE_PATH:

rss_path: rss.xml